"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.tasks_api import TasksApi  # noqa: E501


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_get(self):
        """Test case for tasks_get

        Returns all tasks which are not done yet  # noqa: E501
        """
        pass

    def test_tasks_task_id_complete_post(self):
        """Test case for tasks_task_id_complete_post

        Marks the given task as completed  # noqa: E501
        """
        pass

    def test_tasks_task_id_undo_post(self):
        """Test case for tasks_task_id_undo_post

        Marks the given task as not completed  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
