"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.generic_entity_interactions_api import GenericEntityInteractionsApi  # noqa: E501


class TestGenericEntityInteractionsApi(unittest.TestCase):
    """GenericEntityInteractionsApi unit test stubs"""

    def setUp(self):
        self.api = GenericEntityInteractionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_objects_entity_get(self):
        """Test case for objects_entity_get

        Returns all objects of the given entity  # noqa: E501
        """
        pass

    def test_objects_entity_object_id_delete(self):
        """Test case for objects_entity_object_id_delete

        Deletes a single object of the given entity  # noqa: E501
        """
        pass

    def test_objects_entity_object_id_get(self):
        """Test case for objects_entity_object_id_get

        Returns a single object of the given entity  # noqa: E501
        """
        pass

    def test_objects_entity_object_id_put(self):
        """Test case for objects_entity_object_id_put

        Edits the given object of the given entity  # noqa: E501
        """
        pass

    def test_objects_entity_post(self):
        """Test case for objects_entity_post

        Adds a single object of the given entity  # noqa: E501
        """
        pass

    def test_userfields_entity_object_id_get(self):
        """Test case for userfields_entity_object_id_get

        Returns all userfields with their values of the given object of the given entity  # noqa: E501
        """
        pass

    def test_userfields_entity_object_id_put(self):
        """Test case for userfields_entity_object_id_put

        Edits the given userfields of the given object of the given entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
