"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.user_management_api import UserManagementApi  # noqa: E501


class TestUserManagementApi(unittest.TestCase):
    """UserManagementApi unit test stubs"""

    def setUp(self):
        self.api = UserManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        Returns all users  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        Creates a new user  # noqa: E501
        """
        pass

    def test_users_user_id_delete(self):
        """Test case for users_user_id_delete

        Deletes the given user  # noqa: E501
        """
        pass

    def test_users_user_id_permissions_get(self):
        """Test case for users_user_id_permissions_get

        Returns the assigned permissions of the given user  # noqa: E501
        """
        pass

    def test_users_user_id_permissions_post(self):
        """Test case for users_user_id_permissions_post

        Adds a permission to the given user  # noqa: E501
        """
        pass

    def test_users_user_id_permissions_put(self):
        """Test case for users_user_id_permissions_put

        Replaces the assigned permissions of the given user  # noqa: E501
        """
        pass

    def test_users_user_id_put(self):
        """Test case for users_user_id_put

        Edits the given user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
