"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.location import Location
from openapi_client.model.product import Product
from openapi_client.model.product_barcode import ProductBarcode
from openapi_client.model.quantity_unit import QuantityUnit
globals()['Location'] = Location
globals()['Product'] = Product
globals()['ProductBarcode'] = ProductBarcode
globals()['QuantityUnit'] = QuantityUnit
from openapi_client.model.product_details_response import ProductDetailsResponse


class TestProductDetailsResponse(unittest.TestCase):
    """ProductDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductDetailsResponse(self):
        """Test ProductDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
