"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.chores_api import ChoresApi  # noqa: E501


class TestChoresApi(unittest.TestCase):
    """ChoresApi unit test stubs"""

    def setUp(self):
        self.api = ChoresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chores_chore_id_execute_post(self):
        """Test case for chores_chore_id_execute_post

        Tracks an execution of the given chore  # noqa: E501
        """
        pass

    def test_chores_chore_id_get(self):
        """Test case for chores_chore_id_get

        Returns details of the given chore  # noqa: E501
        """
        pass

    def test_chores_executions_calculate_next_assignments_post(self):
        """Test case for chores_executions_calculate_next_assignments_post

        (Re)calculates all next user assignments of all chores  # noqa: E501
        """
        pass

    def test_chores_executions_execution_id_undo_post(self):
        """Test case for chores_executions_execution_id_undo_post

        Undoes a chore execution  # noqa: E501
        """
        pass

    def test_chores_get(self):
        """Test case for chores_get

        Returns all chores incl. the next estimated execution time per chore  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
