"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.batteries_api import BatteriesApi  # noqa: E501


class TestBatteriesApi(unittest.TestCase):
    """BatteriesApi unit test stubs"""

    def setUp(self):
        self.api = BatteriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batteries_battery_id_charge_post(self):
        """Test case for batteries_battery_id_charge_post

        Tracks a charge cycle of the given battery  # noqa: E501
        """
        pass

    def test_batteries_battery_id_get(self):
        """Test case for batteries_battery_id_get

        Returns details of the given battery  # noqa: E501
        """
        pass

    def test_batteries_charge_cycles_charge_cycle_id_undo_post(self):
        """Test case for batteries_charge_cycles_charge_cycle_id_undo_post

        Undoes a battery charge cycle  # noqa: E501
        """
        pass

    def test_batteries_get(self):
        """Test case for batteries_get

        Returns all batteries incl. the next estimated charge time per battery  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
