"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.error500_error_details import Error500ErrorDetails
globals()['Error500ErrorDetails'] = Error500ErrorDetails
from openapi_client.model.error500 import Error500


class TestError500(unittest.TestCase):
    """Error500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError500(self):
        """Test Error500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Error500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
