"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.stock_by_barcode_api import StockByBarcodeApi  # noqa: E501


class TestStockByBarcodeApi(unittest.TestCase):
    """StockByBarcodeApi unit test stubs"""

    def setUp(self):
        self.api = StockByBarcodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stock_products_by_barcode_barcode_add_post(self):
        """Test case for stock_products_by_barcode_barcode_add_post

        Adds the given amount of the by its barcode given product to stock  # noqa: E501
        """
        pass

    def test_stock_products_by_barcode_barcode_consume_post(self):
        """Test case for stock_products_by_barcode_barcode_consume_post

        Removes the given amount of the by its barcode given product from stock  # noqa: E501
        """
        pass

    def test_stock_products_by_barcode_barcode_get(self):
        """Test case for stock_products_by_barcode_barcode_get

        Returns details of the given product by its barcode  # noqa: E501
        """
        pass

    def test_stock_products_by_barcode_barcode_inventory_post(self):
        """Test case for stock_products_by_barcode_barcode_inventory_post

        Inventories the by its barcode given product (adds/removes based on the given new amount)  # noqa: E501
        """
        pass

    def test_stock_products_by_barcode_barcode_open_post(self):
        """Test case for stock_products_by_barcode_barcode_open_post

        Marks the given amount of the by its barcode given product as opened  # noqa: E501
        """
        pass

    def test_stock_products_by_barcode_barcode_transfer_post(self):
        """Test case for stock_products_by_barcode_barcode_transfer_post

        Transfers the given amount of the by its barcode given product from one location to another (this is currently not supported for tare weight handling enabled products)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
