"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.system_api import SystemApi  # noqa: E501


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_system_config_get(self):
        """Test case for system_config_get

        Returns all config settings  # noqa: E501
        """
        pass

    def test_system_db_changed_time_get(self):
        """Test case for system_db_changed_time_get

        Returns the time when the database was last changed  # noqa: E501
        """
        pass

    def test_system_info_get(self):
        """Test case for system_info_get

        Returns information about the installed grocy, PHP and SQLite version  # noqa: E501
        """
        pass

    def test_system_log_missing_localization_post(self):
        """Test case for system_log_missing_localization_post

        Logs a missing localization string  # noqa: E501
        """
        pass

    def test_system_time_get(self):
        """Test case for system_time_get

        Returns the current server time  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
