"""
    grocy REST API

    Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](http://localhost:8111/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.print_api import PrintApi  # noqa: E501


class TestPrintApi(unittest.TestCase):
    """PrintApi unit test stubs"""

    def setUp(self):
        self.api = PrintApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_print_shoppinglist_thermal_get(self):
        """Test case for print_shoppinglist_thermal_get

        Prints the shoppinglist with a thermal printer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
